version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27019:27019
    volumes:
      - mongo-local:/data/db

  redisdb:
    image: redis
    restart: on-failure:2
    ports:
      - 6379:6379
  
  nodejs:
    ports:
      - 8000:8000
    restart: on-failure
    build: .
    env_file:
      - .env
    depends_on:
      - mongodb
      - redisdb

volumes:
  mongo-local: